set_property PACKAGE_PIN Y11  [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN AA11 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN Y10  [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[*]}]

set_property PACKAGE_PIN Y21  [get_ports {B_0[0]}]
set_property PACKAGE_PIN Y20  [get_ports {B_0[1]}]
set_property PACKAGE_PIN AB20 [get_ports {B_0[2]}]
set_property PACKAGE_PIN AB19 [get_ports {B_0[3]}]
set_property PACKAGE_PIN AB22 [get_ports {G_0[0]}]
set_property PACKAGE_PIN AA22 [get_ports {G_0[1]}]
set_property PACKAGE_PIN AB21 [get_ports {G_0[2]}]
set_property PACKAGE_PIN AA21 [get_ports {G_0[3]}]
set_property PACKAGE_PIN AA19 [get_ports {hsync_0}]
set_property PACKAGE_PIN V20  [get_ports {R_0[0]}]
set_property PACKAGE_PIN U20  [get_ports {R_0[1]}]
set_property PACKAGE_PIN V19  [get_ports {R_0[2]}]
set_property PACKAGE_PIN V18  [get_ports {R_0[3]}]
set_property PACKAGE_PIN Y19  [get_ports {vsync_0}]

set_property IOSTANDARD LVCMOS33 [get_ports {R_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hsync_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {vsync_0}]

set_property PACKAGE_PIN B19  [get_ports {reset_rtl_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset_rtl_0}]
